# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kNbnaRILrzv1mJcC0ZTi-8kZ1UjzNciZ
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Load dataset
print("Loading dataset...")
data = pd.DataFrame({
    'StudyHours': [2,3,4,5,6,7,8,1,3,6],
    'Attendance': [60,65,70,75,80,85,90,50,68,82],
    'SleepHours': [5,6,6,7,7,8,8,4,5,7],
    'AssignmentsCompleted': [40,50,60,65,70,80,90,30,55,75],
    'Performance': ['Poor','Poor','Average','Average','Good','Good','Good','Poor','Average','Good']
})

print("\nDataset Preview:")
print(data.head())

# Convert labels into numbers
performance_mapping = {
    'Poor': 0,
    'Average': 1,
    'Good': 2
}

data['Performance'] = data['Performance'].map(performance_mapping)

# Features and target
X = data[['StudyHours', 'Attendance', 'SleepHours', 'AssignmentsCompleted']]
y = data['Performance']

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Predictions
predictions = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, predictions)

#print(f"\nModel Accuracy: {accuracy * 100:.2f}%")

# Visualization
"""plt.figure(figsize=(8,5))
plt.plot(data['StudyHours'], data['Attendance'], marker='o')
plt.title('Study Hours vs Attendance')
plt.xlabel('Study Hours')
plt.ylabel('Attendance')
plt.grid(True)
plt.show()
print("Graph displayed successfully")"""
# User Input Prediction
print("\nEnter Student Details")

study = float(input("Study Hours: "))
attendance = float(input("Attendance Percentage: "))
sleep = float(input("Sleep Hours: "))
assignment = float(input("Assignments Completed (%): "))

user_data = [[study, attendance, sleep, assignment]]

result = model.predict(user_data)

if result[0] == 0:
    print("\nPredicted Performance: Poor")
elif result[0] == 1:
    print("\nPredicted Performance: Average")
else:
    print("\nPredicted Performance: Good")

# plt.figure(figsize=(8,5))
# plt.plot(data['StudyHours'], data['Attendance'], marker='o')
# plt.title('Study Hours vs Attendance')
# plt.xlabel('Study Hours')
# plt.ylabel('Attendance')
# plt.grid(True)
# plt.show()

# plt.figure(figsize=(8,5))
# plt.plot(data['StudyHours'], data['Attendance'], marker='o')
# plt.title('Study Hours vs Attendance')
# plt.xlabel('Study Hours')
# plt.ylabel('Attendance')
# plt.grid(True)
# plt.show()